dpm install adiciona hash do commit ao datapackage.json dos dados baixados
splor-mg/dpm pull request #79
Opened 2024-08-14 21:52 UTC by labanca

closes #74

* dpm download passa a salvar em cada datapackage.json o commit hash dos dados sendo baixados
* somente URLs do github são consideradas na obtenção dos commit hash
* Funciona para repos públicos e privados (com "token" especificado no data.toml)
* URLs do Github que contenham a hash do commit ainda não são válidas.

2024-08-19 17:55 UTC, fjuniorr requested changes

2024-08-19 17:55 UTC, fjuniorr commented on src/dpm/install.py
> +    branch_name = path_parts[2]
Essa lógica pode ser extraída em uma função dedicada (eg. `parse_rawgithub_url`) de tal forma que seja possível adicionar testes unitários para ela. Uma sugestão de nomes para as propriedades é:

```python
expected = {
  "host": "github",
  "user": "splor-mg",
  "repo": "sisor-dados-2024",
  "ref": "main",
}
assert parse_rawgithub_url("https://raw.githubusercontent.com/splor-mg/sisor-dados-2024/main/datapackage.json") == expected
```

2024-08-19 17:55 UTC, fjuniorr commented on src/dpm/install.py
> +def get_commit_hash(source):
A gente precisa de adicionar suporte para URLs que contenham a hash do commit de cara (tag pode ficar pra depois) porque já usamos isso em repositórios em produção ([exemplo](https://github.com/splor-mg/acordo-judicial-reparacao-vale/blob/7665ad26efd778e2309dd83eea43c5a323f6392e/data.toml)). 

Uma forma de organizar isso com o código que você já tem é:

```python
def resolve_github_ref(ref):
    """
    Given a github reference (branch, tag or commit) returns the commit sha currently associated with it
    """
    if is_commit_sha(ref):
        return ref
    else: 
        return get_commit_hash(ref)
```

Pra função `is_commit_sha` podemos usar regex mesmo:

```python
def is_commit_sha(ref):
    """
    Returns True if ref is a valid commit SHA
    """
    if re.match(r"([a-z0-9]{40})", ref):
        return True
    else:
        return False
    
assert is_commit_sha("main") == False
assert is_commit_sha("5551d0c071f78230dca4656d974e3a36ce52f58c") == True
```

2024-08-19 17:55 UTC, fjuniorr commented on src/dpm/install.py
> +        package.custom.update({'github_commit_hash': get_commit_hash(source)})
Não acho que vamos ter necessariamente caso de uso pra isso, mas já que as informações estão disponíveis podemos armazenar pra além da hash do commit outras informações da URL:

```json
"remote": {
  "host": "github",
  "user": "splor-mg",
  "repo": "sisor-dados-2024",
  "ref": "main",
  "sha": "5551d0c071f78230dca4656d974e3a36ce52f58c"
}
```

2024-08-19 21:22 UTC, labanca commented on src/dpm/install.py
> +def get_commit_hash(source):
Utilizando a url com commit no exemplo o retorno foi:
```json
{
   "host":"raw.githubusercontent.com",
   "user":"splor-mg",
   "repo":"armazem-siad-dados",
   "ref":"dc81c15b04e83eeb3319150c546fcfc41f045af5",
   "sha":"dc81c15b04e83eeb3319150c546fcfc41f045af5"
}
```

Mas também a outro sha dentro do response:

```
response.json()['commit']['tree']['sha']
"3da13c0eacf8be1cdca4d7e9cd0a848df3d22b21"
```

Não sei se é relevante, então mantive o próprio sha que é igual ao da URL de entrada. Apesar do hash do commit já estar na própria URL do data.toml, não evitei de fazer a requisição na API do git. No futuro podemos querer outras informações que virão dela e o custo imagino ser mínimo, além de manter simetria.

```python
if is_commit_sha(parsed_url['ref']):
    api_url = f"https://api.github.com/repos/{parsed_url['user']}/{parsed_url['repo']}/commits/{parsed_url['ref']}"
    response = requests.get(api_url, headers=headers)
    response.raise_for_status()  # Check for request errors

    return {
        "host": parsed_url['host'],
        "user": parsed_url['user'],
        "repo": parsed_url['repo'],
        "ref": parsed_url['ref'],
        "sha": response.json()['sha']
    }
else:
    api_url = f"https://api.github.com/repos/{parsed_url['user']}/{parsed_url['repo']}/branches/{parsed_url['ref']}"
    response = requests.get(api_url, headers=headers)
    response.raise_for_status()  # Check for request errors

    return {
        "host": parsed_url['host'],
        "user": parsed_url['user'],
        "repo": parsed_url['repo'],
        "ref": parsed_url['ref'],
        "sha": response.json()['commit']['sha']
    }
```

2024-08-20 14:40 UTC, fjuniorr requested changes
Você pediu revisão de novo, certo (me perdi nas notificações)? 

## Testes

Na pasta `tests/unit` adiciona testes para as funções `parse_rawgithub_url` e `is_commit_sha` e na pasta `tests/integration` adiciona um teste para a `get_commit_info`.

## DRY

Dá pra remover duplicidade sem perder clareza com:

```python
    github_endpoint = "commits" if is_commit_sha(parsed_url['ref']) else "branches"

    api_url = f"https://api.github.com/repos/{parsed_url['user']}/{parsed_url['repo']}/{github_endpoint}/{parsed_url['ref']}"
    response = requests.get(api_url, headers=headers)
    response.raise_for_status()  # Check for request errors

    return {
        "host": parsed_url['host'],
        "user": parsed_url['user'],
        "repo": parsed_url['repo'],
        "ref": parsed_url['ref'],
        "sha": response.json()['sha']

    }
```

2024-08-20 21:25 UTC, labanca commented
> ```python
>     return {
>         "host": parsed_url['host'],
>         "user": parsed_url['user'],
>         "repo": parsed_url['repo'],
>         "ref": parsed_url['ref'],
>         "sha": response.json()['sha']
> 
>     }
> ```

A chave na qual o SHA fica gravado muda no response dependendo se for branch ou commit, então precisei adaptar a parte final:

```
    return {
        "host": parsed_url['host'],
        "user": parsed_url['user'],
        "repo": parsed_url['repo'],
        "ref": parsed_url['ref'],
        "sha": response.json()['sha'] if github_endpoint == 'commits' else response.json()['commit']['sha']

    }
```

2024-08-21 16:33 UTC, labanca reviewed
Testes criados e alterações realizadas.

2024-08-23 12:24 UTC, merged